# Generated by Django 5.0 on 2024-08-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TituloProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('observacion', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='materia',
            name='denominacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor_interino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interino', to='academico.profesor'),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor_titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titular', to='academico.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='f_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cuil',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='materia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profesor',
            table=None,
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('dni', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.profesor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.familia')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.tituloprofesional'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('dni', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('campo', models.CharField(max_length=100)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.familia')),
            ],
        ),
    ]
