# Generated by Django 5.0 on 2024-08-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_curso_tituloprofesional_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'alumno', 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'verbose_name': 'familia', 'verbose_name_plural': 'familias'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
        migrations.AlterModelOptions(
            name='tituloprofesional',
            options={'verbose_name': 'titulo', 'verbose_name_plural': 'titulos de profes'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'tutor', 'verbose_name_plural': 'tutores'},
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
        migrations.AlterModelTable(
            name='familia',
            table='familias',
        ),
        migrations.AlterModelTable(
            name='materia',
            table='materias',
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='profesores',
        ),
        migrations.AlterModelTable(
            name='tituloprofesional',
            table='titulos_profes',
        ),
        migrations.AlterModelTable(
            name='tutor',
            table='tutores',
        ),
    ]
