# Generated by Django 5.0 on 2024-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_alumno_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='titulo',
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulos',
            field=models.ManyToManyField(to='academico.tituloprofesional'),
        ),
    ]
